name: engage_library
description: A library to build apps at rapid speeds

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  flutter_login: 3.0.0-beta.1
  intl: ^0.17.0
  http: '>=0.13.3'
  provider: ^5.0.0
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.2
  auth_buttons: ^1.0.1+4
  google_sign_in: ^5.0.4
  firebase_messaging: ^10.0.4
  cloud_firestore: ^2.4.0
  cloud_functions: ^3.0.0
  google_mobile_ads: ^0.13.2
  flutter_svg: ^0.22.0
  rxdart: ^0.27.1
  auto_size_text: 3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  datetime_picker_formfield: ^2.0.0
  dropdown_formfield: ^0.1.3
  shared_preferences: ^2.0.6
  universal_platform: ^1.0.0+1
  get: ^4.1.4
  getwidget: ^2.0.4
  flushbar: ^1.10.4
  app_tracking_transparency: ^2.0.1
  timeago: ^3.1.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  file_picker: ^4.0.2
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.9.0'

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/background.png
    - assets/imgs/mountain.jpeg
    - assets/imgs/mountain_medium.jpg
    - assets/imgs/green_background.jpg
    - assets/imgs/space_world.jpeg
    - assets/imgs/space_world_medium.jpg

    - assets/icons/3.png
    - assets/icons/4.png
    - assets/icons/logo_gold_deep.png
    - assets/icons/logo_gold.png
    - assets/icons/logo_green.png

fonts:
  - family: icomoon
    fonts:
      - asset: assets/fonts/IcoMoon.ttf
