name: engage_library
description: library with useful widgets
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  datetime_picker_formfield: ^1.0.0
  multiselect_formfield: ^0.1.2
  dropdown_formfield: ^0.1.1
  smart_select: ^3.0.3
  mask_text_input_formatter: ^1.0.6
  file_picker: ^1.4.3+2
  flutter_icons: ^1.0.0+1
  get: 1.14.1-dev
  image_picker: ^0.6.3+4
  # image_picker_web: ^1.0.3
  dio: ^3.0.9
  flutter_login: ^1.0.14
  badges: ^1.1.1
  # file_picker_cross: ^1.0.0
  loading_overlay: ^0.2.1
  linkwell: ^0.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
